extend = [
	# Build debug and release build [build|release]
	{ path = "pai-make-targets/build.toml" },

	# Fix formatting and clippy [fix|fixfmt|fixclippy|update|clippy]
	{ path = "pai-make-targets/fix.toml" },

	# Publish new crate on crates.io [publish|publishdry]
	{ path = "pai-make-targets/publish.toml" },

	# Test [test]
	{ path = "pai-make-targets/test.toml" },

	# Create a new release
	{ path = "pai-make-targets/createrelease.toml" },
]

# Always update dependencies before a release build
[tasks.release]
dependencies = ["update"]

[tasks.createzips]
env = { OUTNAME = "pai-strace" }

[tasks.uploadrelease]
dependencies = [
	{ name = "publish" },
	{ name = "createzips" },
]
command = "gh"
args = [ "release", "create", "--prerelease", "--generate-notes", "--draft", "v${CARGO_MAKE_CRATE_VERSION}", "./release/${CARGO_MAKE_CRATE_VERSION}/*.zip" ]
