extend = [
	# Build debug and release build [build|release]
	{ path = "pai-make-targets/build.toml" },

	# Fix formatting and clippy [fix|fixfmt|fixclippy|update|clippy]
	{ path = "pai-make-targets/fix.toml" },

	# Publish new crate on crates.io [publish|publishdry]
	{ path = "pai-make-targets/publish.toml" },

	# Create a new release
	{ path = "pai-make-targets/createrelease.toml" },
]

# Always update dependencies before a release build
[tasks.release]
dependencies = ["update"]

[tasks.createzips]
env = { OUTNAME = "pai-strace" }

[tasks.publishrelease]
dependencies = [
	{ name = "update" },
	{ name = "test" },
	{ name = "publish" },
	{ name = "createzips" },
]
command = "gh"
args = [ "release", "create", "--prerelease", "--generate-notes", "--draft", "v${CARGO_MAKE_CRATE_VERSION}", "./release/${CARGO_MAKE_CRATE_VERSION}/*.zip" ]

# Some basic tests to make sure we don't have any fatal errors
[tasks.test1]
command = "cargo"
args = ["run", "--", "-q", "-o", "/dev/null", "--format", "raw", "--format", "json", "id"]
[tasks.test2]
command = "cargo"
args = ["run", "--", "-q", "-o", "/dev/null", "--format", "raw", "--format", "json", "--enrich", "basic", "ls"]
[tasks.test3]
command = "cargo"
args = ["run", "--", "-q", "-o", "/dev/null", "--format", "raw", "--format", "json", "--enrich", "full", "true"]

[tasks.test]
dependencies = ["test1", "test2", "test3"]
