[tasks.build]
command = "cross"
args = ["build", "--target-dir=output", "--target=${@}"]

[tasks.release]
command = "cross"
dependencies = ["update"]
args = ["build", "--frozen", "--target-dir=output", "--release", "--target=${@}"]

[tasks.update]
command = "cargo"
args = ["update"]