[tasks.build]
command = "cross"
args = ["build", "--target-dir=output", "--target=${@}"]

[tasks.fixfmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.fixclippy]
command = "cargo"
install_crate = "clippy"
args = ["clippy", "--no-deps", "--all-targets", "--all-features", "--fix"]

[tasks.releasecheck]
dependencies = ["fixclippy", "fixfmt", "update"]

[tasks.createzips]
dependencies = [
	{ name = "releasecheck" },
	{ name = "createzips", path = "createrelease.toml" },
]

[tasks.githubrelease]
dependencies = [
	{ name = "releasecheck" },
	{ name = "publish" },
	{ name = "createzips", path = "createrelease.toml" },
]
command = "gh"
args = [ "release", "create", "v${CARGO_MAKE_PROJECT_VERSION}", "./release/${CARGO_MAKE_PROJECT_VERSION}/*.zip" ]


[tasks.update]
command = "cargo"
args = ["update"]

[tasks.publish]
dependencies = ["releasecheck"]
command = "cargo"
args = ["publish"]

[tasks.publishdry]
extend = "publish"
args = ["publish", "--dry-run"]

[tasks.clippy]
command = "cargo"
install_crate = "clippy"
args = ["clippy", "--no-deps", "--all-targets", "--all-features"]